### ISSUE TITLE
Invalid structure for AWS, isn't it?

### ISSUE THREAD

**Issue by zack-solvenna** [RedPointGlobal/redpoint-rpi#1]
https://github.com/RedPointGlobal/redpoint-rpi/blob/395e30cf3c4245779619e65c78fbfefb24ae9a92/redpoint-rpi/templates/deploy-volumes.yaml#L61-L82

Installation was failing to allocate a persistent volume until I made these changes:
```yml
---
{{- if eq .Values.global.cloudProvider "amazon" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rpi-fileoutputdir
spec:
  capacity:
    storage: {{ .Values.appsettings.storage.size.rpi_output_directory }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  csi:
    driver: {{ .Values.appsettings.storage.class.amazon.provisioner }}
    readOnly: false
    volumeHandle: {{ .Values.appsettings.storage.class.amazon.volumeHandle }} 
    # volumeAttributes:
    # source: {{ .Values.appsettings.storage.class.amazon.source }} 
    # nodeStageSecretRef:
    # name: {{ .Values.appsettings.storage.class.amazon.nodeStageSecretRef }} 

---
```
